/// HEIC -> JPEG in-process, through the Windows Imaging Component.
///
/// The CLI reaches the same codec by spawning `powershell` (T-0031); an app
/// must not, so this calls WIC's COM interfaces directly over `dart:ffi`.
/// Rejected alternatives: a pub package (none decodes HEIC on Windows -- the
/// `image` package cannot, and the pub.dev HEIC plugins are Android/iOS-only,
/// re-checked 2026-08-14); a C++ plugin in `app/windows/` (that folder is
/// generated by `flutter create` and gitignored, so the code would not be in
/// the repository).
library;

import 'dart:ffi';
import 'dart:io';
import 'dart:isolate';
import 'dart:typed_data';

import 'package:ffi/ffi.dart';

/// A HEIC that could not be turned into JPEG bytes, and why.
class HeicDecodeException implements Exception {
  HeicDecodeException(this.message);

  final String message;

  @override
  String toString() => message;
}

/// Turns HEIC bytes into JPEG bytes, or throws [HeicDecodeException].
typedef HeicDecoder = Future<Uint8List> Function(Uint8List heic);

/// Why [operatingSystem] cannot decode HEIC, or null when it can.
String? heicDecodeUnsupported(String operatingSystem) =>
    operatingSystem == 'windows'
        ? null
        : 'HEIC decoding in this app is Windows-only (it uses the Windows '
            'Imaging Component); convert it to .jpg or .png first';

/// The decoder for this host: WIC on Windows, and elsewhere one that names
/// the platform rather than pretending to try.
HeicDecoder get platformHeicDecoder {
  final unsupported = heicDecodeUnsupported(Platform.operatingSystem);
  if (unsupported != null) {
    return (_) => Future.error(HeicDecodeException(unsupported));
  }
  return windowsHeicToJpeg;
}

/// One 4000x3000 file costs 340-610 ms off the UI isolate (measured
/// 2026-08-14; T-0031 measured 798 ms for the same codec through PowerShell).
Future<Uint8List> windowsHeicToJpeg(Uint8List heic) async {
  final (bytes, error) = await Isolate.run(() => _heicToJpegSync(heic));
  if (bytes == null) throw HeicDecodeException(error!);
  return bytes;
}

// ---------------------------------------------------------------------------
// COM plumbing. Vtable indices are the method order of the interface as
// declared in wincodec.idl, IUnknown's three methods first.

const _sOk = 0;
const _sFalse = 1;
const _rpcEChangedMode = 0x80010106;
const _componentNotFound = 0x88982F50;

const _clsidWicImagingFactory = 'CACAF262-9370-4615-A13B-9F5539DA4C0A';
const _iidWicImagingFactory = 'EC5EC8A9-C395-4314-9C77-54D7A935FF70';
const _containerFormatJpeg = '19E4A5AA-5662-4FC5-A0C0-1758028E1057';
const _pixelFormat24bppBGR = '6FDDC324-4E03-4BFE-B185-3D77768DC90C';

final _ole32 = DynamicLibrary.open('ole32.dll');

final _coInitializeEx = _ole32.lookupFunction<
    Int32 Function(Pointer<Void>, Uint32),
    int Function(Pointer<Void>, int)>('CoInitializeEx');

final _coUninitialize = _ole32
    .lookupFunction<Void Function(), void Function()>('CoUninitialize');

final _coCreateInstance = _ole32.lookupFunction<
    Int32 Function(Pointer<Uint8>, Pointer<Void>, Uint32, Pointer<Uint8>,
        Pointer<Pointer<Void>>),
    int Function(Pointer<Uint8>, Pointer<Void>, int, Pointer<Uint8>,
        Pointer<Pointer<Void>>)>('CoCreateInstance');

final _createStreamOnHGlobal = _ole32.lookupFunction<
    Int32 Function(Pointer<Void>, Int32, Pointer<Pointer<Void>>),
    int Function(
        Pointer<Void>, int, Pointer<Pointer<Void>>)>('CreateStreamOnHGlobal');

/// The GUID's first three fields are little-endian integers and the last is a
/// byte array, so the 16 bytes are not the text order.
Pointer<Uint8> _guid(String text, Allocator alloc) {
  final hex = text.replaceAll('-', '');
  final raw = [
    for (var i = 0; i < 16; i++) int.parse(hex.substring(i * 2, i * 2 + 2), radix: 16)
  ];
  final out = alloc<Uint8>(16);
  for (final (offset, length) in [(0, 4), (4, 2), (6, 2)]) {
    for (var i = 0; i < length; i++) {
      out[offset + i] = raw[offset + length - 1 - i];
    }
  }
  for (var i = 8; i < 16; i++) {
    out[i] = raw[i];
  }
  return out;
}

Pointer<Void> _slot(Pointer<Void> obj, int index) =>
    obj.cast<Pointer<Void>>().value.cast<Pointer<Void>>()[index];

void _release(Pointer<Void> obj) => _slot(obj, 2)
    .cast<NativeFunction<Uint32 Function(Pointer<Void>)>>()
    .asFunction<int Function(Pointer<Void>)>()(obj);

// One helper per argument shape below, named for it: `asFunction` needs the
// signature as a literal type, so a generic call helper is not possible.

int _hr1(Pointer<Void> obj, int index, Pointer<Void> a) => _slot(obj, index)
    .cast<NativeFunction<Int32 Function(Pointer<Void>, Pointer<Void>)>>()
    .asFunction<int Function(Pointer<Void>, Pointer<Void>)>()(obj, a);

int _hr2(Pointer<Void> obj, int index, Pointer<Void> a, Pointer<Void> b) =>
    _slot(obj, index)
        .cast<
            NativeFunction<
                Int32 Function(Pointer<Void>, Pointer<Void>,
                    Pointer<Void>)>>()
        .asFunction<
            int Function(Pointer<Void>, Pointer<Void>, Pointer<Void>)>()(
        obj, a, b);

int _hr3(Pointer<Void> obj, int index, Pointer<Void> a, Pointer<Void> b,
        Pointer<Void> c) =>
    _slot(obj, index)
        .cast<
            NativeFunction<
                Int32 Function(Pointer<Void>, Pointer<Void>, Pointer<Void>,
                    Pointer<Void>)>>()
        .asFunction<
            int Function(Pointer<Void>, Pointer<Void>, Pointer<Void>,
                Pointer<Void>)>()(obj, a, b, c);

int _hrPtrPtrIntPtr(Pointer<Void> obj, int index, Pointer<Void> a,
        Pointer<Void> b, int c, Pointer<Void> d) =>
    _slot(obj, index)
        .cast<
            NativeFunction<
                Int32 Function(Pointer<Void>, Pointer<Void>, Pointer<Void>,
                    Uint32, Pointer<Void>)>>()
        .asFunction<
            int Function(Pointer<Void>, Pointer<Void>, Pointer<Void>, int,
                Pointer<Void>)>()(obj, a, b, c, d);

int _hrPtrIntPtr(Pointer<Void> obj, int index, Pointer<Void> a, int b,
        Pointer<Void> c) =>
    _slot(obj, index)
        .cast<
            NativeFunction<
                Int32 Function(Pointer<Void>, Pointer<Void>, Uint32,
                    Pointer<Void>)>>()
        .asFunction<
            int Function(Pointer<Void>, Pointer<Void>, int,
                Pointer<Void>)>()(obj, a, b, c);

int _hrIntPtr(Pointer<Void> obj, int index, int a, Pointer<Void> b) =>
    _slot(obj, index)
        .cast<
            NativeFunction<
                Int32 Function(Pointer<Void>, Uint32, Pointer<Void>)>>()
        .asFunction<int Function(Pointer<Void>, int, Pointer<Void>)>()(
        obj, a, b);

int _hrPtrInt(Pointer<Void> obj, int index, Pointer<Void> a, int b) =>
    _slot(obj, index)
        .cast<
            NativeFunction<
                Int32 Function(Pointer<Void>, Pointer<Void>, Uint32)>>()
        .asFunction<int Function(Pointer<Void>, Pointer<Void>, int)>()(
        obj, a, b);

int _hrTwoInts(Pointer<Void> obj, int index, int a, int b) => _slot(obj, index)
    .cast<NativeFunction<Int32 Function(Pointer<Void>, Uint32, Uint32)>>()
    .asFunction<int Function(Pointer<Void>, int, int)>()(obj, a, b);

int _hrNone(Pointer<Void> obj, int index) => _slot(obj, index)
    .cast<NativeFunction<Int32 Function(Pointer<Void>)>>()
    .asFunction<int Function(Pointer<Void>)>()(obj);

/// IWICFormatConverter::Initialize -- the only call here with a float
/// argument, which the x64 ABI passes in a different register bank.
int _converterInitialize(Pointer<Void> obj, Pointer<Void> source,
        Pointer<Uint8> format, Pointer<Void> palette) =>
    _slot(obj, 8)
        .cast<
            NativeFunction<
                Int32 Function(Pointer<Void>, Pointer<Void>, Pointer<Uint8>,
                    Uint32, Pointer<Void>, Double, Uint32)>>()
        .asFunction<
            int Function(Pointer<Void>, Pointer<Void>, Pointer<Uint8>, int,
                Pointer<Void>, double, int)>()(
        obj, source, format, 0, palette, 0.0, 0);

int _streamSeek(Pointer<Void> obj) => _slot(obj, 5)
    .cast<
        NativeFunction<
            Int32 Function(Pointer<Void>, Int64, Uint32, Pointer<Void>)>>()
    .asFunction<int Function(Pointer<Void>, int, int, Pointer<Void>)>()(
    obj, 0, 0, nullptr);

String _hex(int hr) =>
    '0x${(hr & 0xFFFFFFFF).toRadixString(16).toUpperCase().padLeft(8, '0')}';

(Uint8List?, String?) _heicToJpegSync(Uint8List heic) {
  final init = _coInitializeEx(nullptr, 0); // COINIT_MULTITHREADED
  if (init != _sOk && init != _sFalse && init != _rpcEChangedMode) {
    return (null, 'COM could not start (CoInitializeEx ${_hex(init)})');
  }
  final ownsCom = init == _sOk || init == _sFalse;

  final arena = Arena();
  final open = <Pointer<Void>>[];
  try {
    Pointer<Void> out(String what, int Function(Pointer<Pointer<Void>>) call) {
      final slot = arena<Pointer<Void>>();
      final hr = call(slot);
      if (hr != _sOk) throw _WicError(what, hr);
      open.add(slot.value);
      return slot.value;
    }

    void check(String what, int hr) {
      if (hr != _sOk) throw _WicError(what, hr);
    }

    final factory = out(
      'the imaging factory',
      (slot) => _coCreateInstance(
        _guid(_clsidWicImagingFactory, arena),
        nullptr,
        1, // CLSCTX_INPROC_SERVER
        _guid(_iidWicImagingFactory, arena),
        slot,
      ),
    );

    final input = arena<Uint8>(heic.length);
    input.asTypedList(heic.length).setAll(0, heic);
    final inStream =
        out('an input stream', (slot) => _hr1(factory, 14, slot.cast()));
    check('reading the file into memory',
        _hrPtrInt(inStream, 16, input.cast(), heic.length));

    final decoder = out(
      'a HEIC decoder',
      (slot) => _hrPtrPtrIntPtr(factory, 4, inStream, nullptr, 0, slot.cast()),
    );
    final frame =
        out('the first image', (slot) => _hrIntPtr(decoder, 13, 0, slot.cast()));

    final converter =
        out('a pixel converter', (slot) => _hr1(factory, 10, slot.cast()));
    check(
      'converting the pixels',
      _converterInitialize(
          converter, frame, _guid(_pixelFormat24bppBGR, arena), nullptr),
    );

    final width = arena<Uint32>();
    final height = arena<Uint32>();
    check('reading the image size',
        _hr2(converter, 3, width.cast(), height.cast()));

    final outStream = out('an output buffer',
        (slot) => _createStreamOnHGlobal(nullptr, 1, slot));
    final encoder = out(
      'a JPEG encoder',
      (slot) => _hr3(factory, 8, _guid(_containerFormatJpeg, arena).cast(),
          nullptr, slot.cast()),
    );
    // WICBitmapEncoderNoCache: the two caching options answer
    // WINCODEC_ERR_UNSUPPORTEDOPERATION here (measured 2026-08-14).
    check('starting the JPEG', _hrPtrInt(encoder, 3, outStream, 2));

    final frameOut =
        out('a JPEG frame', (slot) => _hr2(encoder, 10, slot.cast(), nullptr));
    check('starting the JPEG frame', _hr1(frameOut, 3, nullptr));
    check('sizing the JPEG',
        _hrTwoInts(frameOut, 4, width.value, height.value));
    check('setting the JPEG pixel format',
        _hr1(frameOut, 6, _guid(_pixelFormat24bppBGR, arena).cast()));
    check('encoding the JPEG', _hr2(frameOut, 11, converter, nullptr));
    check('finishing the JPEG frame', _hrNone(frameOut, 12));
    check('finishing the JPEG', _hrNone(encoder, 11));

    // STATSTG is 80 bytes on x64 and cbSize sits after an 8-byte name pointer
    // and a padded DWORD. Sizing it 72 overflows the buffer by the trailing
    // two DWORDs and crashes the VM one call or so later (measured).
    final stat = arena<Uint8>(80);
    check('measuring the JPEG', _hrPtrInt(outStream, 12, stat.cast(), 1));
    final size = stat.cast<Uint64>()[2];
    if (size == 0) return (null, 'the converter produced an empty image');

    check('rewinding the JPEG', _streamSeek(outStream));
    final buffer = arena<Uint8>(size);
    final read = arena<Uint32>();
    check('reading the JPEG back',
        _hrPtrIntPtr(outStream, 3, buffer.cast(), size, read.cast()));
    return (Uint8List.fromList(buffer.asTypedList(read.value)), null);
  } on _WicError catch (e) {
    return (null, e.message);
  } finally {
    for (final obj in open.reversed) {
      _release(obj);
    }
    arena.releaseAll();
    if (ownsCom) _coUninitialize();
  }
}

class _WicError implements Exception {
  _WicError(this.what, this.hr);

  final String what;
  final int hr;

  String get message => (hr & 0xFFFFFFFF) == _componentNotFound
      ? 'Windows has no HEIC codec installed -- install "HEIF Image '
          'Extensions" from the Microsoft Store, or convert the file to .jpg'
      : 'Windows failed at $what (${_hex(hr)})';
}
