/// The GoG installer's own metadata, read where it sits beside the game
/// (T-0157).
///
/// The first [DetectionSource] on T-0155's seam, and the highest-confidence
/// one this product has: `goggame-<gameId>.info` is JSON the publisher's
/// installer wrote, not a read of a photograph or a guess at a file name. So a
/// run over it makes no vision call, costs nothing, has no temperature, no
/// prompt cache and no sampling, and repeats byte for byte for free.
///
/// **The schema is not vendor-documented at field level.** GOG's developer
/// docs establish only the file's existence, name and author -- "a
/// mini-manifest file named *goggame-<dlcID>.info*" in "the root folder of the
/// game", "always automatically generated by our installer"
/// (docs.gog.com/sdk-dlc-discovery/). No page on docs.gog.com states the JSON
/// keys, and no `goggame-*.info` was available to read (no GOG game was
/// installed to have generated one), so the three
/// keys below were taken from generated files quoted in full elsewhere and
/// cross-checked against each other:
///
/// | source | file quoted | `gameId` | `rootGameId` | `name` |
/// | --- | --- | --- | --- | --- |
/// | gog.com forum, "Adding external games to Galaxy" | hand-written, GOG's own instructions | string | string, "should match the gameId" | string, "the game title" |
/// | lutris/lutris#4080 | ATTIC, installer-generated | string | string, equal | string |
/// | Reloaded-III store spec | Paths in the Void SC, installer-generated | string | string, equal | string |
///
/// **Every other key is treated as absent** -- `version`, `buildId`,
/// `clientId`, `language`, `languages`, `playTasks`, `standalone`,
/// `dependencyGameId`. Two of those appear in one of the three files and not
/// in another (`version` is in both generated files and in neither hand-made
/// one), which is exactly why nothing here reads them.
///
/// A shape outside that table is declined rather than guessed at (T-0007's
/// rule is for every reader here, not only the vision one), and the reasons
/// below are constants because [Orchestrator] groups its skip warnings by the
/// reason string -- a reason carrying a per-entry value would produce the one
/// line per row that T-0144 removed.
library;

import 'dart:convert';

import '../models.dart';
import '../orchestrator.dart';

/// Reads `goggame-<gameId>.info` into a detection.
///
/// Takes one [SourceEntry] per `.info` file, which is how the seam hands over
/// a directory holding several of them (T-0155): a base game and each of its
/// DLCs install one apiece, sharing a [SourceEntry.container].
class GogMetadataSource implements DetectionSource {
  const GogMetadataSource();

  /// What the shell enumerates. Case-insensitive because the entry name comes
  /// back from a Windows filesystem, which does not preserve the case anyone
  /// searched with.
  static final RegExp fileName = RegExp(r'^goggame-\d+\.info$', caseSensitive: false);

  /// Prefixes [Detection.sourceId], so a consumer knows whose id it holds
  /// without inferring it from [DetectionOrigin], which names the kind of
  /// source and not the store.
  static const idPrefix = 'gog:';

  /// `PC`, not `GOG` (T-0156). A store name reaches no entry in `platformIds`,
  /// so the IGDB query runs unfiltered and every candidate it brings back is
  /// then compared against a platform *name* that contains no such word --
  /// `platformAgreement` answers `mismatch` and `ResolverWorker._best` refuses
  /// all of them. The hint has to be a platform or the row resolves to
  /// nothing.
  static const platformHint = 'PC';

  /// The hand-over to T-0158: an entry this source has no metadata for is not
  /// a failure, it is a game whose title has to be guessed from its name
  /// instead. Nothing produces a row here and a row there for one entry --
  /// this source claims an entry only by returning an item for it.
  /// [Severity.exclusion], and the paragraph above is the whole argument: this
  /// is a hand-over, not a miss (T-0222).
  static const noMetadata = 'no goggame-*.info metadata beside it';

  // The four below are [Severity.failure]: the file is present and named the
  // way the installer names one, so it is a manifest whose shape is not the
  // shape documented above -- a game that should be here and is not (T-0222).
  static const notJson = 'goggame-*.info is not JSON';
  static const notAnObject = 'goggame-*.info is not a JSON object';
  static const noName = 'goggame-*.info carries no "name" string';
  static const noGameId = 'goggame-*.info carries no "gameId" string';

  /// A DLC's mini-manifest names its parent in `rootGameId`
  /// (docs.gog.com/sdk-dlc-discovery/; measured against Astralane, whose
  /// pre-order DLC carries `gameId 1100000006` under `rootGameId 1100000007`).
  /// Declined rather than merged: the collection being exported is games, a
  /// DLC's `name` is its own and not the base game's, so a row for it would
  /// survive dedupe and reach review as a second game the owner does not have.
  /// [Severity.exclusion] -- the manifest was read and understood (T-0222).
  static const dlcNotAGame = 'goggame-*.info is DLC metadata, not a game';

  @override
  SourceReading read(SourceEntry entry) {
    final content = entry.content;
    if (content == null || !fileName.hasMatch(entry.name)) {
      return _excluded(entry, noMetadata);
    }

    final Object? decoded;
    try {
      decoded = jsonDecode(content);
    } on FormatException {
      return _failed(entry, notJson);
    }
    if (decoded is! Map<String, dynamic>) {
      return _failed(entry, notAnObject);
    }

    final name = decoded['name'];
    if (name is! String || name.trim().isEmpty) {
      return _failed(entry, noName);
    }
    final gameId = decoded['gameId'];
    if (gameId is! String || gameId.trim().isEmpty) {
      return _failed(entry, noGameId);
    }
    final rootGameId = decoded['rootGameId'];
    if (rootGameId is String &&
        rootGameId.trim().isNotEmpty &&
        rootGameId.trim() != gameId.trim()) {
      return _excluded(entry, dlcNotAGame);
    }

    return SourceReading(items: [
      Detection.fromSource(
        rawTitle: name.trim(),
        origin: DetectionOrigin.metadata,
        sourceEntry: entry.name,
        sourceId: '$idPrefix${gameId.trim()}',
        platformHint: platformHint,
      ),
    ]);
  }

  SourceReading _excluded(SourceEntry entry, String reason) =>
      _decline(entry, reason, Severity.exclusion);

  SourceReading _failed(SourceEntry entry, String reason) =>
      _decline(entry, reason, Severity.failure);

  SourceReading _decline(SourceEntry entry, String reason, Severity severity) =>
      SourceReading(declined: [
        DeclinedEntry(name: entry.name, reason: reason, severity: severity)
      ]);
}
